#!/bin/bash

cd code
cd cominisatps
ln -s . minisat
cd simp
MROOT=.. make clean
MROOT=.. make libr
cd ../..

cd uwrmaxsat
make config
make clean
make r
cp -p build/release/bin/uwrmaxsat ../../bin/
rm -rf build
cd ..
rm cominisatps/minisat
cd ..
